# Generated by Django 4.2.14 on 2024-08-02 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='Autor',
        ),
        migrations.RenameModel(
            old_name='Publisher',
            new_name='Editorial',
        ),
        migrations.RenameModel(
            old_name='Book',
            new_name='Libro',
        ),
    ]
